### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by lukas1994** [kensk8er/chicksexer#1]
Hi,
What data was this trained on?

**Comment by lukas1994** [comment]
Never mind, found it.

**Comment by lukas1994** [comment]
Could you add the links to download the raw data please?

**Comment by kensk8er** [comment]
Hi @lukas1994 , thanks for opening the issue, I completely forgot to mention data used add the link! Could you wait until this weekend and I'll try to sort this out.

Ken

**Comment by kensk8er** [comment]
I've added the links to the raw data.
